name: Postman CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '20'

    - name: Create Docs Directory
      run: mkdir -p ./docs

    - name: Install Newman
      run: npm install -g newman

    - name: Run Postman Tests
      run: |
        newman run ./supernatural_collection.json \
          -e ./supernatural_environment.json \
          -g ./supernatural_globals.json \
          --reporters cli,htmlextra \
          --reporter-htmlextra-browserTitle "Report Supernatural" \
          --reporter-htmlextra-title "Report Supernatural" \
          --reporter-htmlextra-export ./docs/index.html

   
    - name: Upload Test Report
      if: success()
      uses: actions/upload-artifact@v1
      with:
          name: test-report
          path: ./docs/index.html

