name: Postman CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

<<<<<<< HEAD
     # Runs a single command using the runners shell
      - name: Step 1 Check version Newman and Node
        run: |
          newman --version
          node --version
          
      # Runs a single command using the runners shell
      - name: Step 2 Install Newman-Reporter-HtmlExtra
        run: sudo npm install -g newman-reporter-htmlextra

  # Runs a single command using the runners shell
      - name: Step 3 Execute collection
        newman run ./Amanda-ApiLockeKey.json -e ./env-automacao.json -g ./env-global.json --delay-request 1 --reporters cli, -r htmlextra --reporter-htmlextra-export ./docs/index.html
=======
  # Runs a single command using the runners shell
    - name: Step 1 Check version Newman and Node
      run: |
          newman --version
          node --version
          
    # Runs a single command using the runners shell
    - name: Step 2 Install Newman-Reporter-HtmlExtra
      run: sudo npm install -g newman-reporter-htmlextra

  # Runs a single command using the runners shell
    - name: Step 3 Execute collection
      run: newman run ./supernatural_collection.json -e ./supernatural_environment.json -g ./supernatural_globals.json --reporters cli, -r htmlextra --reporter-htmlextra-browserTitle "Report API Supernatural" --reporter-htmlextra-title "Report API Supernatural" --reporter-htmlextra-export ./docs/index.html
>>>>>>> 9744e4336758184494d1d1accd82adb7ef0b9c2f

    - name: Upload Test Report
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: ./docs/index.html
